### ISSUE TITLE
Allow default route to default locale

### ISSUE THREAD

**Issue by rwillrich** [museways/translatable_routes#2]
What if we change the scope with the locale parameter to make this optional, and in this case, use default_locale as the value of the locale? One example:

    # config/application.rb
    config.i18n.available_locales = [:pt, :en]
    config.i18n.default_locale = :pt

    # config/routes.rb
    localized do
      root 'home#index'
      get 'profile' => 'profile#index'
    end

And the routes generated be like this:

    root_pt_path => '/'
    root_en_path => ':locale'
    profile_pt_path = 'perfil'
    profile_en_path = ':locale/perfil'

Whould it be possible to implement this?

**Comment by mmontossi** [comment]
Today I was fixing the rails 4.2 compatibility and I started working on this, I notice something important, I agree is nicer but it seems a bad practices in seo, because search engines make assumptions of your folder structure.

Let me use the example you sent:

/perfil
/en/perfil

In that case search engines may get wrong the idea not considering /perfil and /en/perfile related but if you use:

/pt/perfil
/en/perfil

There will be a lot more changes to make search engines understand the idea of different locales.

Please feel free to send your thoughts about this, researching I didn't find any absolutely concluding information.

**Comment by rwillrich** [comment]
Hi! Sorry about the delay in answering, the last days have been crazy.

It is a good point to check before implement this. I'll do some research about this and see the best way we can approach this.
